spring.application.name=messenger-server

# ??????????? ? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/messenger_db
spring.datasource.username=postgres
spring.datasource.password=2204

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true